package main

// This command builds this go file and asm.s without a runtime.
// The overlay.json file can be generated by doing `go run github.com/totallygamerjet/smallestgo`.
//
// go build -trimpath -overlay overlay.json -buildvcs=false -ldflags="-E _start -s -w"

func main() { /* This is empty on purpose */ }
